### PR TITLE
Adding reportType as a user input

### PR DESCRIPTION
**Pull request by eperelli**
fqm-execution-frontend can create both individual and summary measureReports via the UI

### CODE REVIEW

**Comment by mgramigna** [comment]
You'll notice that the automated checks are failing (due to `prettier` formatting). You can check prettier with 

```
npm run prettier
```

If it fails, you can auto fix things with 

```
npm run prettier:fix
```

It will never change any functionality, only code style.

If you wish, there's a way to configure VS Code to auto-format with prettier when you save a file. Instructions [here](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)

**Review by mgramigna — CHANGES_REQUESTED** [review]
ooooo something I found that I didn't anticipate:

We currently do not support the calculation of SDEs or HTML for summary MeasureReports. So what we should probably do in the UI is disable the calculateHTML and calculateSDE buttons when summary measurereport is selected!

To do this, you could add another case to the `disabled` prop of the checkboxes to check for if summary measureReport is selected. You should already have the `calculationOptions` object in that file, so you can make use of the `reportType` property that you've now added

**Review by MegRiley — APPROVED** [review]
Looks good to me

**Review by mgramigna — APPROVED** [review]
wooohoooo first PR!!!!!

**Pull request merged**
